---
title: "Ivoryton Library Donation Data (2004-2017)"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(mosaic)
library(ggplot2)
library(ggthemes)
library(formattable)
library(data.table)
library(stringr)
library(DT)
library(janitor)
```

```{r, echo = FALSE, include=FALSE}
#Loading data
#4-5
data_4_5 <- read.csv("4-5.csv")

data_4_5 <- data_4_5 %>%
  mutate(year = "'04-05")

#5-6
data_5_6 <- read.csv("5-6.csv")

data_5_6 <- data_5_6[1:31, ]

data_5_6 <- data_5_6 %>%
  mutate(year = ifelse(Paid.Amount > 0, "'05-06", "no")) %>%
  select(Num, Name, Paid.Amount, year)

#6-7 
data_6_7 <- read.csv("6-7.csv")

data_6_7 <- data_6_7[1:112, ]

data_6_7 <- data_6_7 %>%
  mutate(year = ifelse(Paid.Amount > 0, "'06-07", "no")) %>%
  select(Num, Name, Paid.Amount, year)

#7-8
data_7_8 <- read.csv("7-8.csv")

data_7_8 <- data_7_8[1:7, ]

data_7_8 <- data_7_8 %>%
  mutate(year = ifelse(Amount > 0, "'07-08", "no")) %>%
  select(Num, Name, Paid.Amount = Amount, year) 

#8-9
data_8_9 <- read.csv("8-9.csv")

data_8_9 <- data_8_9[1:111, ]

data_8_9 <- data_8_9 %>%
  mutate(year = ifelse(Amount > 0, "'08-09", "no")) %>%
  select(Num, Name = Memo, Paid.Amount = Amount, year)

#9-10
data_9_10 <- read.csv("9-10.csv")

data_9_10 <- data_9_10[1:37, ]

data_9_10 <- data_9_10 %>%
  mutate(year = ifelse(Amount > 0, "'09-10", "no")) %>%
  select(Num, Name = Memo, Paid.Amount = Amount, year)

#10-11
data_10_11 <- read.csv("10-11.csv")

data_10_11 <- data_10_11[1:119, ]

data_10_11 <- data_10_11 %>%
  mutate(year = ifelse(Amount > 0, "'10-11", "no")) %>%
  select(Num, Name = Memo, Paid.Amount = Amount, year)

#11-12
data_11_12 <- read.csv("11-12.csv", stringsAsFactors = FALSE)

data_11_12 <- data_11_12[1:66, ]

data_11_12 <- data_11_12 %>%
  mutate(year = ifelse(Amount > 0, "'11-12", "no"), Name = ifelse(Name == "Misc", Memo, Name)) %>%
  select(Num, Name, Paid.Amount = Amount, year)

#12-13
data_12_13 <- read.csv("12-13.csv")

data_12_13 <- data_12_13[1:51, ]

data_12_13 <- data_12_13 %>%
  mutate(year = ifelse(Paid.Amount > 0, "'12-13", "no")) %>%
  select(Num, Name, Paid.Amount, year)

#13-14
data_13_14 <- read.csv("13-14.csv")

data_13_14 <- data_13_14[1:16, ]

data_13_14 <- data_13_14 %>%
  mutate(year = ifelse(Paid.Amount > 0, "'13-14", "no")) %>%
  select(Num, Name, Paid.Amount, year)


#14-15
data_14_15 <- read.csv("14-15.csv")

data_14_15 <- data_14_15[1:154, ]

data_14_15 <- data_14_15 %>%
  mutate(year = ifelse(Paid.Amount > 0, "'14-15", "no")) %>%
  select(Num, Name, Paid.Amount, year)

#15-16
data_15_16 <- read.csv("15-16.csv")

data_15_16 <- data_15_16[1:177, ]

data_15_16 <- data_15_16 %>%
  mutate(year = ifelse(Paid.Amount > 0, "'15-16", "no")) %>%
  select(Num, Name, Paid.Amount, year)

#16-17
data_16_17 <- read.csv("16-17.csv")

data_16_17$Name <- paste(data_16_17$X,data_16_17$X.1)

data_16_17 <- data_16_17 %>%
  mutate(year = ifelse(Paid.Amount > 0, "'16-17", "no"), Num = ifelse(Paid.Amount <0, "yes", NA)) %>%
  select(Num, Name, Paid.Amount, year)

#Making one big dataset
combined.df <- Reduce(function(...) merge(..., all=TRUE), list(data_4_5, data_5_6, data_6_7, data_7_8, data_8_9, data_9_10, data_10_11, data_11_12, data_12_13, data_13_14, data_14_15, data_15_16, data_16_17))

combined.df$Name <- as.character(combined.df$Name)

#Extracting last names, flagging companies, fixing certain last names
combined.df <- combined.df %>%
  arrange(year)%>%
  mutate(last_name = str_extract(Name, "[^ ]+$"), 
         #flagging companies, some still missing (due to extra spaces)
         company =ifelse(Name %in% c("A 2 Z Screen Printing", "Bogaert Construction", "Essex Hardware Company", "Hilliar<d5>s Foreign Motors", "Triangle Building Assoc.", "Ivoryton Tavern Cafe", "AT&T United Way Giving Campaign", "Essex Vision Center", "Unique Euro Cleaners", "Essex Hardware Company", "Clark Development", "Page-Taft Real Estate", "Essex Financial", "The Paul Foundation", "Foxboro Foundation", "Morris Family Foundation", "Aetna Foundation", "Pfizer Foundation", "Ashleigh's Garden", "Just Give", "Clark Group", "C.P. Burdick and Son, Inc.", "Bogaert Construction Co. Inc.", "Mungo Works of Ivoryton", "Swanton Jewelry", "Tower Lab", "George Penniman Architects LLC", "Shadyhill Nursery", "Mather & Pitts", "Essex Financial Services", "Spa Solutions", "Silva & Sons", "Our Lady of Sorrows", "Essex Wine & Spirits"), "yes", "no"), 
         #Trying one fix, need to send to director
         last_name2 = ifelse(Name == "Alvin Wolfgram & Linda Savitsky", "Wolfgram/Savitsky", last_name))

combined.df2 <- combined.df %>%
  arrange(last_name2)
```

```{r, include = FALSE}
#####WRITING CSV
# write.csv(combined.df2, file = "uncleaned data.csv", row.names=FALSE)
#giving to director of library for individual name cleaning
```

```{r, include=FALSE}
#####GOT CLEANED DATA BACK
#Reading in
cleaned_data <- read.csv("cleaned data for r.csv", stringsAsFactors = FALSE)

cleaned_data <- cleaned_data %>%
  arrange(last_name2)
```

```{r, include = FALSE}
#Creating final last name column: if company, keep full name, else keep fixed last name column
cleaned_data <- cleaned_data %>%
  mutate(last_name_final = ifelse(company == "yes", Name, last_name2))
```

###Total Donations per Year
```{r, echo = FALSE}
#How much money donated per year
cleaned_data_grouped <- cleaned_data %>%
  filter(!year %in% c("no", "7-Jun")) %>%
  group_by(year) %>%
  summarise(total_amount = sum(Paid.Amount)) 

#creating variable for ggplot colors
cleaned_data_grouped <- cleaned_data_grouped %>%
  mutate(np_cutoff = ifelse(year %in% c("'13-14", "'14-15", "'15-16", "'16-17"), "var2", "var1"))

###PLOT

ggplot(cleaned_data_grouped, aes(x = year, y = total_amount, group = 1, colour=np_cutoff)) +
  geom_line(size = 1.5) +
  theme_calc() +
  ylab("Total Amount (in $)") +
  scale_y_continuous(breaks = c(2500, 5000, 7500, 10000, 12500, 15000), labels = c("2,500", "5,000", "7,500", "10,000", "12,500", "15,000"))+
  theme(axis.text = element_text(size = 9), axis.title = element_text(size = 12), plot.title = element_text(hjust = 0.5), legend.position = "none") +
  xlab("Year")+
  annotate("text", x = "'13-14", y = 400, label = "Lost Non-Profit Status", fontface =2) +
  scale_color_manual(values=c("#BB9EA0", "#7A060D")) 
  # geom_segment(aes(x = "'16-17", y = 1700, xend = "'14-15", yend = 1200),
  #                 arrow = arrow(length = unit(0.5, "cm")))
```

###Total Donors per Year
```{r, echo = FALSE}
cleaned_data_grpd_donors <- cleaned_data %>%
  filter(!year %in% c("no", "7-Jun")) %>%
  group_by(year) %>%
  summarise(total_donors = n_distinct(last_name_final))

#creating variable for ggplot colors
cleaned_data_grpd_donors <- cleaned_data_grpd_donors %>%
  mutate(np_cutoff = ifelse(year %in% c("'13-14", "'14-15", "'15-16", "'16-17"), "var2", "var1"))

###PLOT
ggplot(cleaned_data_grpd_donors, aes(x = year, y = total_donors, group = 1, colour=np_cutoff)) +
  geom_line(size = 1.5) +
  theme_calc() +
  ylab("Total # of Donors") +
  scale_y_continuous(breaks = c(25, 50, 75, 100, 125, 150), labels = c("25", "50", "75", "100", "125", "150"))+
  theme(axis.text = element_text(size = 9), axis.title = element_text(size = 12), plot.title = element_text(hjust = 0.5), legend.position = "none") +
  xlab("Year")+
  annotate("text", x = "'13-14", y = 8, label = "Lost Non-Profit Status", fontface =2) +
  scale_color_manual(values=c("#BB9EA0", "#7A060D")) 
```


###Top 20 Donors
```{r, echo = FALSE}
cleaned_data <- cleaned_data %>%
  mutate(`Lifetime Member` = ifelse(Paid.Amount >= 1000, "Yes", 
                                    ifelse(last_name_final == "Jamieson", "Yes", "No"))) %>%
  select(-c(Name, last_name, last_name2, Num))

cleaned_data_names <- cleaned_data %>%
  filter(!year == "no") %>%
  group_by(last_name_final) %>%
  summarise(`Total Number of Years` = n_distinct(year), `First Year` = min(year), `Most Recent Year` = max(year), `Total Amount` = sum(Paid.Amount), `Lifetime Member` = max(`Lifetime Member`)) %>%
  arrange(desc(`Total Amount`), desc(`Total Number of Years`)) %>%
  rename(Name = last_name_final)

names_20_sum <- cleaned_data_names[1:20, ]

names_20_sum$`Total Amount` <- as.numeric(names_20_sum$`Total Amount`)

# names_20_sum <- names_20_sum %>%
#   adorn_totals("row")

#manually adding a total column
#Is there a way to do this automatically? (tried above with adorn totals)
names_20_sum <- rbind(names_20_sum, c("", "", "", "", ""))
names_20_sum <- rbind(names_20_sum, c("Total Amount", "", "", "", "$22311.67", ""))

lifetime_bold <- formatter("span", 
  style = x ~ style("font-weight" = ifelse(x == "Yes", "bold", NA))) 

#formatted table (for handout use)
formattable(names_20_sum, list(
  `Lifetime Member` = lifetime_bold, 
  `Total Number of Years` = color_tile("transparent","brown4")))
```

###All Donors
```{r, echo = FALSE}
#DT::datatables for 
as.datatable(formattable(cleaned_data_names, list(
  `Lifetime Member` = lifetime_bold, 
  `Total Number of Years` = color_tile("transparent","brown4"))))
```

